#!/usr/bin/python3

def raise_exception_msg(message=""):
    # On l√®ve manuellement une NameError avec le message fourni en argument
    raise NameError(message)
